TItle alidata
logo : https://alidata123.github.io/top_uk_youtuber/
Show download: True
remote_theme : remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
